// <auto-generated />
using System;
using Hospital.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Infrastructure.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20251222172104_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Domain.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppointmentDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("appointment_date_time");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("doctor_id");

                    b.Property<bool>("IsFollowUp")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_follow_up");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("char(36)")
                        .HasColumnName("patient_id");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("room_number");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_appointments_doctor_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_appointments_patient_id");

                    b.ToTable("appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b90a5a17-5364-4c3c-8dd5-9b1e0ec4be09"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 3, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("8efc51d1-ad5d-4f9a-a9fa-1e1d67e665e8"),
                            IsFollowUp = false,
                            PatientId = new Guid("7e6d96bc-ac36-47a2-a09b-f671ed094570"),
                            RoomNumber = "101a"
                        },
                        new
                        {
                            Id = new Guid("9dc011e9-d231-4035-ba24-5a781f1e9849"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 3, 16, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("00e3797d-409e-43ce-8524-3acdaa6ea730"),
                            IsFollowUp = true,
                            PatientId = new Guid("7b84c310-4e6f-4369-a41d-f4590e40c596"),
                            RoomNumber = "205"
                        },
                        new
                        {
                            Id = new Guid("efeee871-68d6-49fe-bf0a-abe54c67b322"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 3, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("0bd859e7-41c5-4872-966a-83d28466d220"),
                            IsFollowUp = false,
                            PatientId = new Guid("38db15f1-f410-4fdd-8ae4-009aaabcd7d8"),
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = new Guid("2e54c00a-6784-4cae-a618-a24141cc997d"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2025, 8, 27, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("be04fe70-5e98-49a1-b9e9-73fba7419da0"),
                            IsFollowUp = true,
                            PatientId = new Guid("7b84c310-4e6f-4369-a41d-f4590e40c596"),
                            RoomNumber = "302"
                        },
                        new
                        {
                            Id = new Guid("acdcc23e-a457-4141-b478-f0f04bbcf313"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 3, 16, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("8efc51d1-ad5d-4f9a-a9fa-1e1d67e665e8"),
                            IsFollowUp = true,
                            PatientId = new Guid("eb7dc1f2-1131-4fef-b36a-183996c4f224"),
                            RoomNumber = "205b"
                        },
                        new
                        {
                            Id = new Guid("75df2b96-c3d7-4279-9325-509fce49bcc1"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2025, 9, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("371c0f3f-1bbb-40fa-8eb1-7e755a4ca230"),
                            IsFollowUp = false,
                            PatientId = new Guid("2e812a2a-8ccf-451f-bec9-d22abc0ce387"),
                            RoomNumber = "111"
                        },
                        new
                        {
                            Id = new Guid("c2dfdda5-3d00-4f70-b732-f2d96bbda44c"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2025, 9, 3, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("12d89e4f-2cb4-47df-b7dd-e31977805ce6"),
                            IsFollowUp = true,
                            PatientId = new Guid("65ad0c88-bfc1-454f-9cb0-f70f2fa76edd"),
                            RoomNumber = "402"
                        },
                        new
                        {
                            Id = new Guid("adc63525-2d03-4825-9e92-c03ccfdc45fc"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 2, 16, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("7d9c6f1a-39e4-4834-9d9c-84eb0ee6b51c"),
                            IsFollowUp = true,
                            PatientId = new Guid("81d8168d-01e1-4efe-8177-418648f47c8a"),
                            RoomNumber = "217a"
                        },
                        new
                        {
                            Id = new Guid("79513998-9403-4899-95c6-8c9822f59e88"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 8, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("48800168-8cb8-482b-9b21-13ccc9e9e5b4"),
                            IsFollowUp = false,
                            PatientId = new Guid("47805386-754c-4c1c-b248-000ee803b496"),
                            RoomNumber = "102"
                        },
                        new
                        {
                            Id = new Guid("dda29f9f-2d45-4340-83d5-139e9f03f210"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2025, 9, 18, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("646de129-7522-4b68-9a49-61ae5eb74b11"),
                            IsFollowUp = true,
                            PatientId = new Guid("1773f4a2-6ac9-4b15-9833-8732419eec4b"),
                            RoomNumber = "101a"
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("passport_number");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("specialization_id");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("int")
                        .HasColumnName("year_of_birth");

                    b.HasKey("Id")
                        .HasName("pk_doctors");

                    b.HasIndex("SpecializationId")
                        .HasDatabaseName("ix_doctors_specialization_id");

                    b.ToTable("doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8efc51d1-ad5d-4f9a-a9fa-1e1d67e665e8"),
                            ExperienceYears = 20,
                            FullName = "Сидоров Алексей Петрович",
                            PassportNumber = "6211 100001",
                            SpecializationId = new Guid("153922c2-d6b3-45b4-a3d3-a4e8f2b6c36b"),
                            YearOfBirth = 1975
                        },
                        new
                        {
                            Id = new Guid("00e3797d-409e-43ce-8524-3acdaa6ea730"),
                            ExperienceYears = 15,
                            FullName = "Кузнецова Елена Владимировна",
                            PassportNumber = "6311 100002",
                            SpecializationId = new Guid("27bcf4af-b769-4593-98c1-c27a716ee15c"),
                            YearOfBirth = 1980
                        },
                        new
                        {
                            Id = new Guid("0bd859e7-41c5-4872-966a-83d28466d220"),
                            ExperienceYears = 12,
                            FullName = "Петров Дмитрий Иванович",
                            PassportNumber = "6411 100003",
                            SpecializationId = new Guid("84300ed6-61d2-4dca-bd2c-cb5231c3580c"),
                            YearOfBirth = 1982
                        },
                        new
                        {
                            Id = new Guid("be04fe70-5e98-49a1-b9e9-73fba7419da0"),
                            ExperienceYears = 18,
                            FullName = "Павлова Ольга Сергеевна",
                            PassportNumber = "6511 100004",
                            SpecializationId = new Guid("a018227a-57bf-4e3e-bea9-24ab89683fa3"),
                            YearOfBirth = 1978
                        },
                        new
                        {
                            Id = new Guid("371c0f3f-1bbb-40fa-8eb1-7e755a4ca230"),
                            ExperienceYears = 10,
                            FullName = "Попов Михаил Александрович",
                            PassportNumber = "6611 100005",
                            SpecializationId = new Guid("85c11f07-8f4f-4a32-b9ac-a0a9372feb4f"),
                            YearOfBirth = 1985
                        },
                        new
                        {
                            Id = new Guid("5ee38cbd-121b-49c3-8de9-50da2cf8ef89"),
                            ExperienceYears = 7,
                            FullName = "Смирнова Татьяна Николаевна",
                            PassportNumber = "6711 100006",
                            SpecializationId = new Guid("c71552c5-4b28-4f0c-a62c-ac131a519059"),
                            YearOfBirth = 1990
                        },
                        new
                        {
                            Id = new Guid("12d89e4f-2cb4-47df-b7dd-e31977805ce6"),
                            ExperienceYears = 25,
                            FullName = "Васильев Андрей Викторович",
                            PassportNumber = "6811 100007",
                            SpecializationId = new Guid("acef342c-afab-46f1-8405-64a47d52ae94"),
                            YearOfBirth = 1970
                        },
                        new
                        {
                            Id = new Guid("7d9c6f1a-39e4-4834-9d9c-84eb0ee6b51c"),
                            ExperienceYears = 9,
                            FullName = "Федорова Наталья Игоревна",
                            PassportNumber = "6911 100008",
                            SpecializationId = new Guid("c21f32c0-7e92-4f30-b563-ead686408d99"),
                            YearOfBirth = 1988
                        },
                        new
                        {
                            Id = new Guid("48800168-8cb8-482b-9b21-13ccc9e9e5b4"),
                            ExperienceYears = 30,
                            FullName = "Алексеев Геннадий Степанович",
                            PassportNumber = "6011 100009",
                            SpecializationId = new Guid("153922c2-d6b3-45b4-a3d3-a4e8f2b6c36b"),
                            YearOfBirth = 1965
                        },
                        new
                        {
                            Id = new Guid("646de129-7522-4b68-9a49-61ae5eb74b11"),
                            ExperienceYears = 14,
                            FullName = "Дмитриева Светлана Олеговна",
                            PassportNumber = "6723 100010",
                            SpecializationId = new Guid("27bcf4af-b769-4593-98c1-c27a716ee15c"),
                            YearOfBirth = 1983
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int")
                        .HasColumnName("blood_group");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("passport_number");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<int>("RhFactor")
                        .HasColumnType("int")
                        .HasColumnName("rh_factor");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.ToTable("patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e6d96bc-ac36-47a2-a09b-f671ed094570"),
                            Address = "ул. Карбышева, д. 81, кв. 46",
                            BloodGroup = 1,
                            DateOfBirth = new DateOnly(2001, 9, 13),
                            FullName = "Ряхов Вячеслав Вячеславович",
                            Gender = 0,
                            PassportNumber = "5321 143649",
                            PhoneNumber = "+79372165498",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("7b84c310-4e6f-4369-a41d-f4590e40c596"),
                            Address = "ул. Ленина, д. 25, кв. 12",
                            BloodGroup = 0,
                            DateOfBirth = new DateOnly(1980, 5, 17),
                            FullName = "Петрова Мария Сергеевна",
                            Gender = 1,
                            PassportNumber = "1234 234567",
                            PhoneNumber = "+79279037779",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("38db15f1-f410-4fdd-8ae4-009aaabcd7d8"),
                            Address = "пр. Победы, д. 15, кв. 8",
                            BloodGroup = 2,
                            DateOfBirth = new DateOnly(1985, 3, 10),
                            FullName = "Сидоров Петр Алексеевич",
                            Gender = 0,
                            PassportNumber = "4567 345678",
                            PhoneNumber = "+79279037780",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("df83ef59-220f-4650-a068-180fa0d3b081"),
                            Address = "ул. Советская, д. 7, кв. 3",
                            BloodGroup = 3,
                            DateOfBirth = new DateOnly(1992, 12, 5),
                            FullName = "Козлова Анна Викторовна",
                            Gender = 1,
                            PassportNumber = "2893 456789",
                            PhoneNumber = "+79279037781",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("eb7dc1f2-1131-4fef-b36a-183996c4f224"),
                            Address = "ул. Гагарина, д. 33, кв. 15",
                            BloodGroup = 1,
                            DateOfBirth = new DateOnly(1978, 7, 18),
                            FullName = "Николаев Дмитрий Олегович",
                            Gender = 0,
                            PassportNumber = " 6745 567890",
                            PhoneNumber = "+79279037782",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("2e812a2a-8ccf-451f-bec9-d22abc0ce387"),
                            Address = "ул. Мира, д. 12, кв. 9",
                            BloodGroup = 0,
                            DateOfBirth = new DateOnly(1988, 2, 28),
                            FullName = "Орлова Екатерина Игоревна",
                            Gender = 1,
                            PassportNumber = "2230 678901",
                            PhoneNumber = "+79279037783",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("47805386-754c-4c1c-b248-000ee803b496"),
                            Address = "пр. Независимости, д. 45, кв. 22",
                            BloodGroup = 2,
                            DateOfBirth = new DateOnly(1995, 9, 14),
                            FullName = "Павлов Сергей Николаевич",
                            Gender = 0,
                            PassportNumber = "1245 789012",
                            PhoneNumber = "+79279037784",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("81d8168d-01e1-4efe-8177-418648f47c8a"),
                            Address = "ул. Фрунзе, д. 18, кв. 6",
                            BloodGroup = 1,
                            DateOfBirth = new DateOnly(1983, 11, 30),
                            FullName = "Романова Ольга Дмитриевна",
                            Gender = 1,
                            PassportNumber = "6748 890123",
                            PhoneNumber = "+79279037785",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("65ad0c88-bfc1-454f-9cb0-f70f2fa76edd"),
                            Address = "ул. Кирова, д. 27, кв. 11",
                            BloodGroup = 3,
                            DateOfBirth = new DateOnly(1975, 4, 25),
                            FullName = "Семенов Александр Петрович",
                            Gender = 0,
                            PassportNumber = "1100 901234",
                            PhoneNumber = "+79279037786",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("1773f4a2-6ac9-4b15-9833-8732419eec4b"),
                            Address = "ул. Пушкинская, д. 9, кв. 4",
                            BloodGroup = 0,
                            DateOfBirth = new DateOnly(1998, 6, 8),
                            FullName = "Тихонова Ирина Васильевna",
                            Gender = 1,
                            PassportNumber = "4232 012345",
                            PhoneNumber = "+79279037787",
                            RhFactor = 1
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Models.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_specializations");

                    b.ToTable("specializations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("153922c2-d6b3-45b4-a3d3-a4e8f2b6c36b"),
                            Name = "Терапевт"
                        },
                        new
                        {
                            Id = new Guid("84300ed6-61d2-4dca-bd2c-cb5231c3580c"),
                            Name = "Хирург"
                        },
                        new
                        {
                            Id = new Guid("27bcf4af-b769-4593-98c1-c27a716ee15c"),
                            Name = "Кардиолог"
                        },
                        new
                        {
                            Id = new Guid("a018227a-57bf-4e3e-bea9-24ab89683fa3"),
                            Name = "Невролог"
                        },
                        new
                        {
                            Id = new Guid("85c11f07-8f4f-4a32-b9ac-a0a9372feb4f"),
                            Name = "Офтальмолог"
                        },
                        new
                        {
                            Id = new Guid("c71552c5-4b28-4f0c-a62c-ac131a519059"),
                            Name = "Стоматолог"
                        },
                        new
                        {
                            Id = new Guid("acef342c-afab-46f1-8405-64a47d52ae94"),
                            Name = "Педиатр"
                        },
                        new
                        {
                            Id = new Guid("c21f32c0-7e92-4f30-b563-ead686408d99"),
                            Name = "Дерматолог"
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Models.Appointment", b =>
                {
                    b.HasOne("Hospital.Domain.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_doctors_doctor_id");

                    b.HasOne("Hospital.Domain.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_patients_patient_id");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital.Domain.Models.Doctor", b =>
                {
                    b.HasOne("Hospital.Domain.Models.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctors_specializations_specialization_id");

                    b.Navigation("Specialization");
                });
#pragma warning restore 612, 618
        }
    }
}
