// <auto-generated />
using System;
using Hospital.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Infrastructure.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    partial class HospitalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Domain.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("AppointmentDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsFollowUp")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a6fef7d6-d3ba-4ca1-a3d9-55edf6bc754d"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 3, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("bdf704b9-5148-478b-bacd-521426544ff4"),
                            IsFollowUp = false,
                            PatientId = new Guid("ffcbcb1d-127d-429f-bc5c-a35ee026c33d"),
                            RoomNumber = "101a"
                        },
                        new
                        {
                            Id = new Guid("c6bef0fe-3894-47a2-9c6c-cdfaddf71174"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 3, 16, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("c9dd12bb-e6d5-48f5-9541-56576583eefa"),
                            IsFollowUp = true,
                            PatientId = new Guid("84886119-b39b-4606-bfe3-0fa6985dcaa5"),
                            RoomNumber = "205"
                        },
                        new
                        {
                            Id = new Guid("52e16433-6552-428c-a66a-60a147276ac8"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 3, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("e2dfec7a-776d-431a-867b-979404f052f1"),
                            IsFollowUp = false,
                            PatientId = new Guid("f27a334d-3821-439e-8784-f37b36268e33"),
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = new Guid("3520f47d-1dd0-40c7-a4e3-5d63e8dba7f7"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2025, 8, 27, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("a7bce7d0-f4a4-4ef4-bb65-377884ac1015"),
                            IsFollowUp = true,
                            PatientId = new Guid("84886119-b39b-4606-bfe3-0fa6985dcaa5"),
                            RoomNumber = "302"
                        },
                        new
                        {
                            Id = new Guid("68f8d574-93ed-4d32-a9d0-3679de9d1b38"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 3, 16, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("bdf704b9-5148-478b-bacd-521426544ff4"),
                            IsFollowUp = true,
                            PatientId = new Guid("bdfdd5e0-31e9-4b2d-824e-f92db05e8c72"),
                            RoomNumber = "205b"
                        },
                        new
                        {
                            Id = new Guid("6f83f992-ed65-4f26-8b2b-891d73e5f5b4"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2025, 9, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("f3ca1450-b9ec-4d25-b8ee-d9e2a61e73e6"),
                            IsFollowUp = false,
                            PatientId = new Guid("4ec3b071-eb38-4e0c-a337-afeb0629a51b"),
                            RoomNumber = "111"
                        },
                        new
                        {
                            Id = new Guid("ad221b3e-ec15-4438-bfe3-34639f93436f"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2025, 9, 3, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("a300295d-c48b-44f6-872e-b6cf5a4edc7a"),
                            IsFollowUp = true,
                            PatientId = new Guid("e9cbc97c-badf-40f5-963c-d5d814c3534d"),
                            RoomNumber = "402"
                        },
                        new
                        {
                            Id = new Guid("9bf0a789-7c46-4050-9a13-9445fec63464"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 2, 16, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("c52621b2-aa10-4eca-8fbd-7fd7bf51eef5"),
                            IsFollowUp = true,
                            PatientId = new Guid("8b5bed9a-c816-4cb2-934b-d96fd3c8066a"),
                            RoomNumber = "217a"
                        },
                        new
                        {
                            Id = new Guid("0b1d9298-0c6f-40c6-8c9e-f42b3147f210"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 8, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("4fbe7fd4-f2db-4413-a69f-a50a55dff21e"),
                            IsFollowUp = false,
                            PatientId = new Guid("b25a1128-c1dc-4f14-a3b7-f527868cd100"),
                            RoomNumber = "102"
                        },
                        new
                        {
                            Id = new Guid("5531f4e3-4086-41ad-a1b3-b7918466b142"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2025, 9, 18, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("00274149-82c2-486d-8d64-80df5e49e091"),
                            IsFollowUp = true,
                            PatientId = new Guid("b734dc6b-662c-4e70-9e53-9aba02b32e4d"),
                            RoomNumber = "101a"
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("char(36)");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bdf704b9-5148-478b-bacd-521426544ff4"),
                            ExperienceYears = 20,
                            FullName = "Сидоров Алексей Петрович",
                            PassportNumber = "6211 100001",
                            SpecializationId = new Guid("f2a372c5-9d78-4c28-8ec8-b2b03dfefbfa"),
                            YearOfBirth = 1975
                        },
                        new
                        {
                            Id = new Guid("c9dd12bb-e6d5-48f5-9541-56576583eefa"),
                            ExperienceYears = 15,
                            FullName = "Кузнецова Елена Владимировна",
                            PassportNumber = "6311 100002",
                            SpecializationId = new Guid("b92db95e-74f4-48d7-8952-70926642c9c3"),
                            YearOfBirth = 1980
                        },
                        new
                        {
                            Id = new Guid("e2dfec7a-776d-431a-867b-979404f052f1"),
                            ExperienceYears = 12,
                            FullName = "Петров Дмитрий Иванович",
                            PassportNumber = "6411 100003",
                            SpecializationId = new Guid("354be342-95fe-41b0-a378-8bff19227199"),
                            YearOfBirth = 1982
                        },
                        new
                        {
                            Id = new Guid("a7bce7d0-f4a4-4ef4-bb65-377884ac1015"),
                            ExperienceYears = 18,
                            FullName = "Павлова Ольга Сергеевна",
                            PassportNumber = "6511 100004",
                            SpecializationId = new Guid("e9f77cd0-40a8-464f-8e18-350d23b115fd"),
                            YearOfBirth = 1978
                        },
                        new
                        {
                            Id = new Guid("f3ca1450-b9ec-4d25-b8ee-d9e2a61e73e6"),
                            ExperienceYears = 10,
                            FullName = "Попов Михаил Александрович",
                            PassportNumber = "6611 100005",
                            SpecializationId = new Guid("86b74fd3-0836-44cb-8c20-ac42e0b3738c"),
                            YearOfBirth = 1985
                        },
                        new
                        {
                            Id = new Guid("377ec49b-732c-47c8-8de6-4727dd65f535"),
                            ExperienceYears = 7,
                            FullName = "Смирнова Татьяна Николаевна",
                            PassportNumber = "6711 100006",
                            SpecializationId = new Guid("81607380-1e87-40d7-8bb1-bc26b876e11d"),
                            YearOfBirth = 1990
                        },
                        new
                        {
                            Id = new Guid("a300295d-c48b-44f6-872e-b6cf5a4edc7a"),
                            ExperienceYears = 25,
                            FullName = "Васильев Андрей Викторович",
                            PassportNumber = "6811 100007",
                            SpecializationId = new Guid("5ad2ad3a-f8a0-4f15-9444-5c9220f86947"),
                            YearOfBirth = 1970
                        },
                        new
                        {
                            Id = new Guid("c52621b2-aa10-4eca-8fbd-7fd7bf51eef5"),
                            ExperienceYears = 9,
                            FullName = "Федорова Наталья Игоревна",
                            PassportNumber = "6911 100008",
                            SpecializationId = new Guid("90eb8e02-009f-465e-bbce-5c6d5369a9f9"),
                            YearOfBirth = 1988
                        },
                        new
                        {
                            Id = new Guid("4fbe7fd4-f2db-4413-a69f-a50a55dff21e"),
                            ExperienceYears = 30,
                            FullName = "Алексеев Геннадий Степанович",
                            PassportNumber = "6011 100009",
                            SpecializationId = new Guid("f2a372c5-9d78-4c28-8ec8-b2b03dfefbfa"),
                            YearOfBirth = 1965
                        },
                        new
                        {
                            Id = new Guid("00274149-82c2-486d-8d64-80df5e49e091"),
                            ExperienceYears = 14,
                            FullName = "Дмитриева Светлана Олеговна",
                            PassportNumber = "6723 100010",
                            SpecializationId = new Guid("b92db95e-74f4-48d7-8952-70926642c9c3"),
                            YearOfBirth = 1983
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RhFactor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffcbcb1d-127d-429f-bc5c-a35ee026c33d"),
                            Address = "ул. Карбышева, д. 81, кв. 46",
                            BloodGroup = 1,
                            DateOfBirth = new DateOnly(2001, 9, 13),
                            FullName = "Ряхов Вячеслав Вячеславович",
                            Gender = 0,
                            PassportNumber = "5321 143649",
                            PhoneNumber = "+79372165498",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("84886119-b39b-4606-bfe3-0fa6985dcaa5"),
                            Address = "ул. Ленина, д. 25, кв. 12",
                            BloodGroup = 0,
                            DateOfBirth = new DateOnly(1980, 5, 17),
                            FullName = "Петрова Мария Сергеевна",
                            Gender = 1,
                            PassportNumber = "1234 234567",
                            PhoneNumber = "+79279037779",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("f27a334d-3821-439e-8784-f37b36268e33"),
                            Address = "пр. Победы, д. 15, кв. 8",
                            BloodGroup = 2,
                            DateOfBirth = new DateOnly(1985, 3, 10),
                            FullName = "Сидоров Петр Алексеевич",
                            Gender = 0,
                            PassportNumber = "4567 345678",
                            PhoneNumber = "+79279037780",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("2006ceae-7aa4-4efb-b34c-155b711537f8"),
                            Address = "ул. Советская, д. 7, кв. 3",
                            BloodGroup = 3,
                            DateOfBirth = new DateOnly(1992, 12, 5),
                            FullName = "Козлова Анна Викторовна",
                            Gender = 1,
                            PassportNumber = "2893 456789",
                            PhoneNumber = "+79279037781",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("bdfdd5e0-31e9-4b2d-824e-f92db05e8c72"),
                            Address = "ул. Гагарина, д. 33, кв. 15",
                            BloodGroup = 1,
                            DateOfBirth = new DateOnly(1978, 7, 18),
                            FullName = "Николаев Дмитрий Олегович",
                            Gender = 0,
                            PassportNumber = " 6745 567890",
                            PhoneNumber = "+79279037782",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("4ec3b071-eb38-4e0c-a337-afeb0629a51b"),
                            Address = "ул. Мира, д. 12, кв. 9",
                            BloodGroup = 0,
                            DateOfBirth = new DateOnly(1988, 2, 28),
                            FullName = "Орлова Екатерина Игоревна",
                            Gender = 1,
                            PassportNumber = "2230 678901",
                            PhoneNumber = "+79279037783",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("b25a1128-c1dc-4f14-a3b7-f527868cd100"),
                            Address = "пр. Независимости, д. 45, кв. 22",
                            BloodGroup = 2,
                            DateOfBirth = new DateOnly(1995, 9, 14),
                            FullName = "Павлов Сергей Николаевич",
                            Gender = 0,
                            PassportNumber = "1245 789012",
                            PhoneNumber = "+79279037784",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("8b5bed9a-c816-4cb2-934b-d96fd3c8066a"),
                            Address = "ул. Фрунзе, д. 18, кв. 6",
                            BloodGroup = 1,
                            DateOfBirth = new DateOnly(1983, 11, 30),
                            FullName = "Романова Ольга Дмитриевна",
                            Gender = 1,
                            PassportNumber = "6748 890123",
                            PhoneNumber = "+79279037785",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("e9cbc97c-badf-40f5-963c-d5d814c3534d"),
                            Address = "ул. Кирова, д. 27, кв. 11",
                            BloodGroup = 3,
                            DateOfBirth = new DateOnly(1975, 4, 25),
                            FullName = "Семенов Александр Петрович",
                            Gender = 0,
                            PassportNumber = "1100 901234",
                            PhoneNumber = "+79279037786",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("b734dc6b-662c-4e70-9e53-9aba02b32e4d"),
                            Address = "ул. Пушкинская, д. 9, кв. 4",
                            BloodGroup = 0,
                            DateOfBirth = new DateOnly(1998, 6, 8),
                            FullName = "Тихонова Ирина Васильевna",
                            Gender = 1,
                            PassportNumber = "4232 012345",
                            PhoneNumber = "+79279037787",
                            RhFactor = 1
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Models.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2a372c5-9d78-4c28-8ec8-b2b03dfefbfa"),
                            Name = "Терапевт"
                        },
                        new
                        {
                            Id = new Guid("354be342-95fe-41b0-a378-8bff19227199"),
                            Name = "Хирург"
                        },
                        new
                        {
                            Id = new Guid("b92db95e-74f4-48d7-8952-70926642c9c3"),
                            Name = "Кардиолог"
                        },
                        new
                        {
                            Id = new Guid("e9f77cd0-40a8-464f-8e18-350d23b115fd"),
                            Name = "Невролог"
                        },
                        new
                        {
                            Id = new Guid("86b74fd3-0836-44cb-8c20-ac42e0b3738c"),
                            Name = "Офтальмолог"
                        },
                        new
                        {
                            Id = new Guid("81607380-1e87-40d7-8bb1-bc26b876e11d"),
                            Name = "Стоматолог"
                        },
                        new
                        {
                            Id = new Guid("5ad2ad3a-f8a0-4f15-9444-5c9220f86947"),
                            Name = "Педиатр"
                        },
                        new
                        {
                            Id = new Guid("90eb8e02-009f-465e-bbce-5c6d5369a9f9"),
                            Name = "Дерматолог"
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Models.Appointment", b =>
                {
                    b.HasOne("Hospital.Domain.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital.Domain.Models.Doctor", b =>
                {
                    b.HasOne("Hospital.Domain.Models.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");
                });
#pragma warning restore 612, 618
        }
    }
}
