// <auto-generated />
using System;
using Hospital.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Infrastructure.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    partial class HospitalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Domain.Models.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppointmentDateTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("appointment_date_time");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("doctor_id");

                    b.Property<bool>("IsFollowUp")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_follow_up");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("char(36)")
                        .HasColumnName("patient_id");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("room_number");

                    b.HasKey("Id")
                        .HasName("pk_appointments");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_appointments_doctor_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_appointments_patient_id");

                    b.ToTable("appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e750e7f5-620c-46bd-bf9a-a450c1f9856e"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 3, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("d0e1cb98-d7dd-49c5-8605-ff68176c3160"),
                            IsFollowUp = false,
                            PatientId = new Guid("9838ccd2-7a54-4bd2-9eba-2891913accd9"),
                            RoomNumber = "101a"
                        },
                        new
                        {
                            Id = new Guid("633f8f1d-cdc0-425e-8780-4807970946f5"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 3, 16, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("510c69f9-31a1-430d-85ef-a4967de4ce49"),
                            IsFollowUp = true,
                            PatientId = new Guid("701c8638-70ff-475a-97d8-c7014916e158"),
                            RoomNumber = "205"
                        },
                        new
                        {
                            Id = new Guid("4f2c1a01-f573-40a7-a06b-3e394be9ca0f"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 3, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("63477dbe-81bf-4eef-ada4-1c698440548d"),
                            IsFollowUp = false,
                            PatientId = new Guid("efe1f4d8-4c12-4b50-b82e-9b3a4878657d"),
                            RoomNumber = "101"
                        },
                        new
                        {
                            Id = new Guid("82324979-ff64-45af-bf79-8f628ada5fc9"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2025, 8, 27, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("63d138c0-74c7-4fee-85c1-447e592b5ed0"),
                            IsFollowUp = true,
                            PatientId = new Guid("701c8638-70ff-475a-97d8-c7014916e158"),
                            RoomNumber = "302"
                        },
                        new
                        {
                            Id = new Guid("09a636f2-fff7-459d-8cf4-dd3430d5f342"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 3, 16, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("d0e1cb98-d7dd-49c5-8605-ff68176c3160"),
                            IsFollowUp = true,
                            PatientId = new Guid("b10a50d2-4cb6-42c1-83da-a6c7117aeeac"),
                            RoomNumber = "205b"
                        },
                        new
                        {
                            Id = new Guid("a50dd755-4af8-4a1d-a5b6-b8ead24a892e"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2025, 9, 12, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("625e23fc-240a-4db3-99c5-32e4e2e17676"),
                            IsFollowUp = false,
                            PatientId = new Guid("2db0cc68-8de3-4340-b824-6149e9845e89"),
                            RoomNumber = "111"
                        },
                        new
                        {
                            Id = new Guid("a8495792-da0a-459a-9c0e-7369522e53ad"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2025, 9, 3, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("d2ad7cab-939e-41c1-9b98-b1a9d1c1e67a"),
                            IsFollowUp = true,
                            PatientId = new Guid("99b30229-b463-464f-88ea-0107fc41b0a0"),
                            RoomNumber = "402"
                        },
                        new
                        {
                            Id = new Guid("f288fb39-6460-48ac-a4d6-f27cd687e862"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 2, 16, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("1e598b02-c3be-4572-aaaf-2afa1853619e"),
                            IsFollowUp = true,
                            PatientId = new Guid("b524fb6a-0b69-4b3b-b9eb-6a0e6c4a56ad"),
                            RoomNumber = "217a"
                        },
                        new
                        {
                            Id = new Guid("f6d62c69-2f26-486d-8189-f38b4552e683"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2024, 8, 17, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("bd99c5f1-3697-4e0d-bd22-af813a063a5e"),
                            IsFollowUp = false,
                            PatientId = new Guid("d165e993-705a-44ef-b340-df1dcc4bae09"),
                            RoomNumber = "102"
                        },
                        new
                        {
                            Id = new Guid("77a922cc-4719-4e4e-91af-7dc2d8c8694f"),
                            AppointmentDateTime = new DateTimeOffset(new DateTime(2025, 9, 18, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DoctorId = new Guid("4809a06b-78a1-4bac-b4a3-4b69a814c4c1"),
                            IsFollowUp = true,
                            PatientId = new Guid("09d0cf7d-84bd-4c9b-8a40-9d7da02a75a8"),
                            RoomNumber = "101a"
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("experience_years");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("passport_number");

                    b.Property<Guid>("SpecializationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("specialization_id");

                    b.Property<int>("YearOfBirth")
                        .HasColumnType("int")
                        .HasColumnName("year_of_birth");

                    b.HasKey("Id")
                        .HasName("pk_doctors");

                    b.HasIndex("SpecializationId")
                        .HasDatabaseName("ix_doctors_specialization_id");

                    b.ToTable("doctors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0e1cb98-d7dd-49c5-8605-ff68176c3160"),
                            ExperienceYears = 20,
                            FullName = "Сидоров Алексей Петрович",
                            PassportNumber = "6211 100001",
                            SpecializationId = new Guid("2ddda41b-811b-4207-8d62-7bd6f380302e"),
                            YearOfBirth = 1975
                        },
                        new
                        {
                            Id = new Guid("510c69f9-31a1-430d-85ef-a4967de4ce49"),
                            ExperienceYears = 15,
                            FullName = "Кузнецова Елена Владимировна",
                            PassportNumber = "6311 100002",
                            SpecializationId = new Guid("d893ad2c-ae54-4eaa-8092-36bf3c0aa882"),
                            YearOfBirth = 1980
                        },
                        new
                        {
                            Id = new Guid("63477dbe-81bf-4eef-ada4-1c698440548d"),
                            ExperienceYears = 12,
                            FullName = "Петров Дмитрий Иванович",
                            PassportNumber = "6411 100003",
                            SpecializationId = new Guid("9526c9b9-9bc2-4ba2-8c5d-d5f37f4a9ddc"),
                            YearOfBirth = 1982
                        },
                        new
                        {
                            Id = new Guid("63d138c0-74c7-4fee-85c1-447e592b5ed0"),
                            ExperienceYears = 18,
                            FullName = "Павлова Ольга Сергеевна",
                            PassportNumber = "6511 100004",
                            SpecializationId = new Guid("f5bd5316-537e-48d2-86e2-ccb75e907d4c"),
                            YearOfBirth = 1978
                        },
                        new
                        {
                            Id = new Guid("625e23fc-240a-4db3-99c5-32e4e2e17676"),
                            ExperienceYears = 10,
                            FullName = "Попов Михаил Александрович",
                            PassportNumber = "6611 100005",
                            SpecializationId = new Guid("b2e11556-ddd6-4f73-a282-83e04cae99b6"),
                            YearOfBirth = 1985
                        },
                        new
                        {
                            Id = new Guid("83a896b2-a6c4-4468-84fc-26399a3db1ff"),
                            ExperienceYears = 7,
                            FullName = "Смирнова Татьяна Николаевна",
                            PassportNumber = "6711 100006",
                            SpecializationId = new Guid("d93d55bd-6914-4b1f-94fd-774f974dd3f3"),
                            YearOfBirth = 1990
                        },
                        new
                        {
                            Id = new Guid("d2ad7cab-939e-41c1-9b98-b1a9d1c1e67a"),
                            ExperienceYears = 25,
                            FullName = "Васильев Андрей Викторович",
                            PassportNumber = "6811 100007",
                            SpecializationId = new Guid("8f100466-4664-4124-8ef9-0268f6d20718"),
                            YearOfBirth = 1970
                        },
                        new
                        {
                            Id = new Guid("1e598b02-c3be-4572-aaaf-2afa1853619e"),
                            ExperienceYears = 9,
                            FullName = "Федорова Наталья Игоревна",
                            PassportNumber = "6911 100008",
                            SpecializationId = new Guid("a3d48bd8-dc4a-4b05-b3dc-57bde5ba751c"),
                            YearOfBirth = 1988
                        },
                        new
                        {
                            Id = new Guid("bd99c5f1-3697-4e0d-bd22-af813a063a5e"),
                            ExperienceYears = 30,
                            FullName = "Алексеев Геннадий Степанович",
                            PassportNumber = "6011 100009",
                            SpecializationId = new Guid("2ddda41b-811b-4207-8d62-7bd6f380302e"),
                            YearOfBirth = 1965
                        },
                        new
                        {
                            Id = new Guid("4809a06b-78a1-4bac-b4a3-4b69a814c4c1"),
                            ExperienceYears = 14,
                            FullName = "Дмитриева Светлана Олеговна",
                            PassportNumber = "6723 100010",
                            SpecializationId = new Guid("d893ad2c-ae54-4eaa-8092-36bf3c0aa882"),
                            YearOfBirth = 1983
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int")
                        .HasColumnName("blood_group");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gender");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("passport_number");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<int>("RhFactor")
                        .HasColumnType("int")
                        .HasColumnName("rh_factor");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.ToTable("patients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9838ccd2-7a54-4bd2-9eba-2891913accd9"),
                            Address = "ул. Карбышева, д. 81, кв. 46",
                            BloodGroup = 1,
                            DateOfBirth = new DateOnly(2001, 9, 13),
                            FullName = "Ряхов Вячеслав Вячеславович",
                            Gender = 0,
                            PassportNumber = "5321 143649",
                            PhoneNumber = "+79372165498",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("701c8638-70ff-475a-97d8-c7014916e158"),
                            Address = "ул. Ленина, д. 25, кв. 12",
                            BloodGroup = 0,
                            DateOfBirth = new DateOnly(1980, 5, 17),
                            FullName = "Петрова Мария Сергеевна",
                            Gender = 1,
                            PassportNumber = "1234 234567",
                            PhoneNumber = "+79279037779",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("efe1f4d8-4c12-4b50-b82e-9b3a4878657d"),
                            Address = "пр. Победы, д. 15, кв. 8",
                            BloodGroup = 2,
                            DateOfBirth = new DateOnly(1985, 3, 10),
                            FullName = "Сидоров Петр Алексеевич",
                            Gender = 0,
                            PassportNumber = "4567 345678",
                            PhoneNumber = "+79279037780",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("f3c54e7b-e4c3-48b0-ae13-8d74b6c89f2e"),
                            Address = "ул. Советская, д. 7, кв. 3",
                            BloodGroup = 3,
                            DateOfBirth = new DateOnly(1992, 12, 5),
                            FullName = "Козлова Анна Викторовна",
                            Gender = 1,
                            PassportNumber = "2893 456789",
                            PhoneNumber = "+79279037781",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("b10a50d2-4cb6-42c1-83da-a6c7117aeeac"),
                            Address = "ул. Гагарина, д. 33, кв. 15",
                            BloodGroup = 1,
                            DateOfBirth = new DateOnly(1978, 7, 18),
                            FullName = "Николаев Дмитрий Олегович",
                            Gender = 0,
                            PassportNumber = " 6745 567890",
                            PhoneNumber = "+79279037782",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("2db0cc68-8de3-4340-b824-6149e9845e89"),
                            Address = "ул. Мира, д. 12, кв. 9",
                            BloodGroup = 0,
                            DateOfBirth = new DateOnly(1988, 2, 28),
                            FullName = "Орлова Екатерина Игоревна",
                            Gender = 1,
                            PassportNumber = "2230 678901",
                            PhoneNumber = "+79279037783",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("d165e993-705a-44ef-b340-df1dcc4bae09"),
                            Address = "пр. Независимости, д. 45, кв. 22",
                            BloodGroup = 2,
                            DateOfBirth = new DateOnly(1995, 9, 14),
                            FullName = "Павлов Сергей Николаевич",
                            Gender = 0,
                            PassportNumber = "1245 789012",
                            PhoneNumber = "+79279037784",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = new Guid("b524fb6a-0b69-4b3b-b9eb-6a0e6c4a56ad"),
                            Address = "ул. Фрунзе, д. 18, кв. 6",
                            BloodGroup = 1,
                            DateOfBirth = new DateOnly(1983, 11, 30),
                            FullName = "Романова Ольга Дмитриевна",
                            Gender = 1,
                            PassportNumber = "6748 890123",
                            PhoneNumber = "+79279037785",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("99b30229-b463-464f-88ea-0107fc41b0a0"),
                            Address = "ул. Кирова, д. 27, кв. 11",
                            BloodGroup = 3,
                            DateOfBirth = new DateOnly(1975, 4, 25),
                            FullName = "Семенов Александр Петрович",
                            Gender = 0,
                            PassportNumber = "1100 901234",
                            PhoneNumber = "+79279037786",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = new Guid("09d0cf7d-84bd-4c9b-8a40-9d7da02a75a8"),
                            Address = "ул. Пушкинская, д. 9, кв. 4",
                            BloodGroup = 0,
                            DateOfBirth = new DateOnly(1998, 6, 8),
                            FullName = "Тихонова Ирина Васильевna",
                            Gender = 1,
                            PassportNumber = "4232 012345",
                            PhoneNumber = "+79279037787",
                            RhFactor = 1
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Models.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_specializations");

                    b.ToTable("specializations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ddda41b-811b-4207-8d62-7bd6f380302e"),
                            Name = "Терапевт"
                        },
                        new
                        {
                            Id = new Guid("9526c9b9-9bc2-4ba2-8c5d-d5f37f4a9ddc"),
                            Name = "Хирург"
                        },
                        new
                        {
                            Id = new Guid("d893ad2c-ae54-4eaa-8092-36bf3c0aa882"),
                            Name = "Кардиолог"
                        },
                        new
                        {
                            Id = new Guid("f5bd5316-537e-48d2-86e2-ccb75e907d4c"),
                            Name = "Невролог"
                        },
                        new
                        {
                            Id = new Guid("b2e11556-ddd6-4f73-a282-83e04cae99b6"),
                            Name = "Офтальмолог"
                        },
                        new
                        {
                            Id = new Guid("d93d55bd-6914-4b1f-94fd-774f974dd3f3"),
                            Name = "Стоматолог"
                        },
                        new
                        {
                            Id = new Guid("8f100466-4664-4124-8ef9-0268f6d20718"),
                            Name = "Педиатр"
                        },
                        new
                        {
                            Id = new Guid("a3d48bd8-dc4a-4b05-b3dc-57bde5ba751c"),
                            Name = "Дерматолог"
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Models.Appointment", b =>
                {
                    b.HasOne("Hospital.Domain.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_doctors_doctor_id");

                    b.HasOne("Hospital.Domain.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_appointments_patients_patient_id");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital.Domain.Models.Doctor", b =>
                {
                    b.HasOne("Hospital.Domain.Models.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_doctors_specializations_specialization_id");

                    b.Navigation("Specialization");
                });
#pragma warning restore 612, 618
        }
    }
}
