<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.RabbitMQ.Client" Version="13.1.0" />
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hospital.Contracts\Hospital.Contracts.csproj" />
    <ProjectReference Include="..\Hospital.Domain\Hospital.Domain.csproj" />
  </ItemGroup>

</Project>
